### This notebook introduces the learner to the concept of DataFrames found in the Pandas package

In [1]:
import pandas as pd

#### Example 1: Creating a DataFrame from a list of lists

In [2]:
# Create a list of lists containing data
list_df = [[32, 'Portugal', 94], [30, 'Argentina', 93], [25, 'Brazil', 92]]

# Create index - names of players
index = ['Christiano Ronaldo', 'Lionel Messi', 'Neymar']

# Create column names
columns = ['Age', 'Nationality', 'Overall']

# Create a DataFrame by passing in data, index, and columns
pd.DataFrame(data=list_df, index=index, columns=columns)

                    Age Nationality  Overall
Christiano Ronaldo   32    Portugal       94
Lionel Messi         30   Argentina       93
Neymar               25      Brazil       92

#### Example 2: Creating a DataFrame from a dictionary

In [3]:
# Create a dictionary containing data
dict_df = {'Age' : [32, 30, 25], 'Nationality' : ['Portugal', 'Argentina', 'Brazil'], 'Overall' : [94, 93, 92]}

# Create index - names of players
index = ['Christiano Ronaldo', 'Lionel Messi', 'Neymar']

# Create a dataframe by passing in data, index, and columns
pd.DataFrame(data=dict_df, index=index)

                    Age Nationality  Overall
Christiano Ronaldo   32    Portugal       94
Lionel Messi         30   Argentina       93
Neymar               25      Brazil       92

#### Example 3: Creating a DataFrame from NumPy arrays

In [5]:
import numpy as np

In [7]:
# Create NumPy array containing data
array_df = np.array([[32, 'Portugal', 94], [30, 'Argentina', 93], [25, 'Brazil', 92]])

# Create index - names of players
index = ['Christiano Ronaldo', 'Lionel Messi', 'Neymar']

# Create Column names
columns = ['Age', 'Nationality', 'Overall']

# Create a DataFrame by passing in data, index, and columns
pd.DataFrame(data=array_df, index=index, columns=columns)

                   Age Nationality Overall
Christiano Ronaldo  32    Portugal      94
Lionel Messi        30   Argentina      93
Neymar              25      Brazil      92

#### Example 4: Creating a Pandas DataFrame from a CSV file

In [9]:
# Load data - pass 'Name' as our index column.
# For this exercise, we'll use football player data to evaluate our Data Frame.
load_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/fundamentals/football_players.csv', index_col='Name')

# Create a DataFrame called df
df = pd.DataFrame(load_df)

# use the head() function to look at the first 5 rows
df.head()

C:\Users\steph\AppData\Local\Temp\ipykernel_33408\1077786811.py:3: DtypeWarning: Columns (14,26) have mixed types. Specify dtype option on import or set low_memory=False.
  load_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/fundamentals/football_players.csv', index_col='Name')

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,
Cristiano Ronaldo,32,Portugal,94,89,63,89,63,93,95,85,...,83,94,23,91,92,31,80,85,88,ST LW
L. Messi,30,Argentina,93,92,48,90,95,95,96,77,...,88,85,26,87,73,28,59,90,85,RW
Neymar,25,Brazil,92,94,56,96,82,95,92,75,...,81,80,33,90,78,24,53,80,83,LW
L. Suárez,30,Uruguay,92,88,78,86,60,91,83,77,...,83,87,38,77,89,45,80,84,88,ST
M. Neuer,31,Germany,92,58,29,52,35,48,70,15,...,55,25,11,61,44,10,83,70,11,GK

### Accessing data within DataFrames

In [11]:
# Select the 5th row using iloc[]
df.iloc[4]

Age                         31
Nationality            Germany
Overall                     92
Acceleration            58
Aggression              29
Agility                 52
Balance                 35
Ball control            48
Composure               70
Crossing                15
Curve                   14
Dribbling               30
Finishing               13
Free kick accuracy      11
GK diving               91
GK handling             90
GK kicking              95
GK positioning          91
GK reflexes             89
Heading accuracy        25
Interceptions           30
Jumping                 78
Long passing            59
Long shots              16
Marking                 10
Penalties               47
Positioning             12
Reactions               85
Short passing           55
Shot power              25
Sliding tackle          11
Sprint speed            61
Stamina                 44
Standing tackle         10
Strength                83
Vision                  70
Volleys                 11
Preferred Positions        GK
Name: M. Neuer, dtype: object

In [13]:
# Select rows 5 to 10
df.iloc[4:10]

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,
M. Neuer,31,Germany,92,58,29,52,35,48,70,15,...,55,25,11,61,44,10,83,70,11,GK
R. Lewandowski,28,Poland,91,79,80,78,80,89,87,62,...,83,88,19,83,79,42,84,78,87,ST
De Gea,26,Spain,90,57,38,60,43,42,64,17,...,50,31,13,58,40,21,64,68,13,GK
E. Hazard,26,Belgium,90,93,54,93,91,92,87,80,...,86,79,22,87,79,27,65,86,79,LW
T. Kroos,27,Germany,90,60,60,71,69,89,85,85,...,90,87,69,52,77,82,74,88,82,CDM CM
G. Higuaín,29,Argentina,90,78,50,75,69,85,86,68,...,75,88,18,80,72,22,85,70,88,ST

In [15]:
# Select the M. Neur index using loc[]
df.loc['M. Neuer']

Age                         31
Nationality            Germany
Overall                     92
Acceleration            58
Aggression              29
Agility                 52
Balance                 35
Ball control            48
Composure               70
Crossing                15
Curve                   14
Dribbling               30
Finishing               13
Free kick accuracy      11
GK diving               91
GK handling             90
GK kicking              95
GK positioning          91
GK reflexes             89
Heading accuracy        25
Interceptions           30
Jumping                 78
Long passing            59
Long shots              16
Marking                 10
Penalties               47
Positioning             12
Reactions               85
Short passing           55
Shot power              25
Sliding tackle          11
Sprint speed            61
Stamina                 44
Standing tackle         10
Strength                83
Vision                  70
Volleys                 11
Preferred Positions        GK
Name: M. Neuer, dtype: object

#### Example 6: Accessing DataFrame data by Column

In [17]:
# Select the Column 'Age'
df['Age']

Name
Cristiano Ronaldo    32
L. Messi             30
Neymar               25
L. Suárez            30
M. Neuer             31
                     ..
A. Kelsey            17
B. Richardson        47
J. Young             17
J. Lundstram         18
L. Sackey            18
Name: Age, Length: 17981, dtype: int64

In [19]:
# Select the columns 'Age' and 'Nationality'
df[['Age', 'Nationality']]

                   Age Nationality
Name
Cristiano Ronaldo   32    Portugal
L. Messi            30   Argentina
Neymar              25      Brazil
L. Suárez           30     Uruguay
M. Neuer            31     Germany
...                ...         ...
A. Kelsey           17     England
B. Richardson       47     England
J. Young            17    Scotland
J. Lundstram        18     England
L. Sackey           18       Ghana

[17981 rows x 2 columns]

#### Exercise 7: Selecting a subset of the DataFrame using indices and Columns in combination

In [21]:
# Select the first 5 rows and first 2 columns - Rows first
df.iloc[0:5][['Age', 'Nationality']]

                   Age Nationality
Name
Cristiano Ronaldo   32    Portugal
L. Messi            30   Argentina
Neymar              25      Brazil
L. Suárez           30     Uruguay
M. Neuer            31     Germany

In [22]:
# Select the first 5 rows and first 2 columns - columns first
df[['Age', 'Nationality']].iloc[0:5]

                   Age Nationality
Name
Cristiano Ronaldo   32    Portugal
L. Messi            30   Argentina
Neymar              25      Brazil
L. Suárez           30     Uruguay
M. Neuer            31     Germany