## This notebook walks the learner throug the process of manipulating, transforming, and altering Pandas DataFrames

In [2]:
import pandas as pd

In [3]:
# load data - pass 'Name' as our index column
df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/fundamentals/football_players.csv', index_col='Name')

# use the head() function to look at the first 5 rows
df.head()

C:\Users\steph\AppData\Local\Temp\ipykernel_25016\3391866340.py:2: DtypeWarning: Columns (14,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/fundamentals/football_players.csv', index_col='Name')

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,
Cristiano Ronaldo,32,Portugal,94,89,63,89,63,93,95,85,...,83,94,23,91,92,31,80,85,88,ST LW
L. Messi,30,Argentina,93,92,48,90,95,95,96,77,...,88,85,26,87,73,28,59,90,85,RW
Neymar,25,Brazil,92,94,56,96,82,95,92,75,...,81,80,33,90,78,24,53,80,83,LW
L. Suárez,30,Uruguay,92,88,78,86,60,91,83,77,...,83,87,38,77,89,45,80,84,88,ST
M. Neuer,31,Germany,92,58,29,52,35,48,70,15,...,55,25,11,61,44,10,83,70,11,GK

## Sorting

#### Sorting by age from youngest to oldest (select first 5 entries)

In [4]:
df.sort_values(by='Age').head()

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,
J. Romero,16,Argentina,58,75,36,70,86,55,59,46,...,52,54,25,77,58,26,41,51,45,ST
J. Hove,16,Norway,51,57,57,58,56,51,42,40,...,56,50,56,64,47,51,54,56,29,CM
Javi Vázquez,16,Spain,58,61,53,48,65,47,43,33,...,41,42,59,64,59,63,55,37,29,CB
K. Pierie,16,Netherlands,65,72,64,66,53,65,66,47,...,68,35,62,72,45,67,65,56,32,LB CB
L. Pintor,16,France,54,72,29,70,68,56,43,27,...,30,57,12,68,36,10,34,38,48,ST

#### Sorting by age from youngest to oldest (select first 5 entries), then by overall, also descending

In [5]:
df.sort_values(by=['Age', 'Overall']).head()

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,
J. Hove,16,Norway,51,57,57,58,56,51,42,40,...,56,50,56,64,47,51,54,56,29,CM
R. Strechie,16,Romania,54,64,51,63,61,52,47,43,...,60,52,50,61,61,54,62,53,28,CM
L. Pintor,16,France,54,72,29,70,68,56,43,27,...,30,57,12,68,36,10,34,38,48,ST
V. Barbero,16,Argentina,54,73,34,76,77,48,52,52,...,50,51,25,75,60,25,42,48,50,RM
M. Sprang,16,Germany,57,18,12,19,29,10,18,12,...,19,17,13,16,32,14,38,59,12,GK

#### Sorting by age from oldest to youngest (Select first 5 entries).

In [6]:
df.sort_values(by='Age', ascending=False).head()

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,
B. Richardson,47,England,46,25,44,35,44,22,44,11,...,12,13,13,25,32,12,47,17,12,GK
E. El Hadary,44,Egypt,70,28,29,21,41,25,57,20,...,16,18,15,39,34,19,73,16,12,GK
O. Pérez,44,Mexico,71,60,26,69,69,23,50,19,...,26,24,11,57,41,12,66,40,13,GK
J. Walker,43,England,55,22,41,53,64,38,35,16,...,22,22,13,35,19,11,62,32,11,GK
D. Coyne,43,Wales,55,36,36,48,58,31,57,13,...,28,21,19,33,37,16,76,33,11,GK

## Filtering

#### Filtering on players older than 30

In [7]:
df[df['Age'] > 30]

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,
Cristiano Ronaldo,32,Portugal,94,89,63,89,63,93,95,85,...,83,94,23,91,92,31,80,85,88,ST LW
M. Neuer,31,Germany,92,58,29,52,35,48,70,15,...,55,25,11,61,44,10,83,70,11,GK
Sergio Ramos,31,Spain,90,75,84,79,60,84,80,66,...,78,79,91,77,84,89,81,63,66,CB
L. Modrić,31,Croatia,89,75,62,93,94,92,84,78,...,92,73,73,71,82,80,58,90,74,CDM CM
G. Chiellini,32,Italy,89,68,92,59,64,57,82,58,...,59,78,90,78,68,92,91,50,45,CB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P. Jennings,37,England,52,38,40,54,50,22,46,18,...,35,24,12,38,37,13,43,21,14,GK
K. Tokushige,33,Japan,51,25,18,38,39,12,41,12,...,31,20,12,20,23,13,62,33,5,GK
H. Tanaka,34,Japan,49,41,92,58,78,42,47,44,...,57,48,49,55,76,41,56,42,35,CDM CM
Y. Uchimura,32,Japan,48,40,31,33,65,57,62,51,...,60,40,42,39,29,42,37,47,38,CAM
B. Richardson,47,England,46,25,44,35,44,22,44,11,...,12,13,13,25,32,12,47,17,12,GK

#### Filtering on more than one condition

In [8]:
df[(df['Age'] > 30) & (df['Overall'] > 90)]

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,
Cristiano Ronaldo,32,Portugal,94,89,63,89,63,93,95,85,...,83,94,23,91,92,31,80,85,88,ST LW
M. Neuer,31,Germany,92,58,29,52,35,48,70,15,...,55,25,11,61,44,10,83,70,11,GK

#### Creating new Columns from existing columns in a Pandas DataFrame

In [9]:
# Create a column of rating per yaer of age
df['Rating Per Year of Age'] = df['Overall'] / df['Age']

df['Rating Per Year of Age'].head()

Name
Cristiano Ronaldo    2.937500
L. Messi             3.100000
Neymar               3.680000
L. Suárez            3.066667
M. Neuer             2.967742
Name: Rating Per Year of Age, dtype: float64

#### Deleting Columns using the drop() function

In [10]:
# Drop the column we just created above
df = df.drop('Rating Per Year of Age', axis=1)

df.head()

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,
Cristiano Ronaldo,32,Portugal,94,89,63,89,63,93,95,85,...,83,94,23,91,92,31,80,85,88,ST LW
L. Messi,30,Argentina,93,92,48,90,95,95,96,77,...,88,85,26,87,73,28,59,90,85,RW
Neymar,25,Brazil,92,94,56,96,82,95,92,75,...,81,80,33,90,78,24,53,80,83,LW
L. Suárez,30,Uruguay,92,88,78,86,60,91,83,77,...,83,87,38,77,89,45,80,84,88,ST
M. Neuer,31,Germany,92,58,29,52,35,48,70,15,...,55,25,11,61,44,10,83,70,11,GK

## Grouping Data

In [12]:
# Let's look at the average rating by age (first 5 rows)
df.groupby('Age')[['Overall']].mean().head()

       Overall
Age
16   57.846154
17   56.089147
18   57.287202
19   59.430309
20   61.559839

In [14]:
# Look at the average rating by age and nationaloty (first 15 rows)
df.groupby(['Age', 'Nationality'])[['Overall']].mean().head(15)

                   Overall
Age Nationality
16  Argentina    56.000000
    England      61.500000
    France       54.000000
    Germany      57.000000
    Italy        61.000000
    Netherlands  62.000000
    Norway       54.500000
    Romania      54.000000
    Spain        58.000000
17  Algeria      54.000000
    Argentina    57.333333
    Australia    52.000000
    Austria      54.500000
    Belgium      58.250000
    Canada       56.000000

## Transforming Data

In [15]:
# Applying a custom function to a dataframe
def year_to_month(x):
    "converts no of years to no of months"
    return x * 12

In [17]:
# Change the age column to months and look at the first 5 entries
df['Age'].apply(year_to_month).head()

Name
Cristiano Ronaldo    384
L. Messi             360
Neymar               300
L. Suárez            360
M. Neuer             372
Name: Age, dtype: int64

In [19]:
# Using a lambda function on a DataFrame
year_to_month_lamb = lambda x: x * 12

In [22]:
# print function answer
print('def: ', year_to_month(30))
print('lambda: ', year_to_month_lamb(30))

def:  360
lambda:  360

In [25]:
# Change the age column to months and look at the first 5 entries
df['Age'].apply(lambda x: x * 12).head()

Name
Cristiano Ronaldo    384
L. Messi             360
Neymar               300
L. Suárez            360
M. Neuer             372
Name: Age, dtype: int64

In [27]:
# Create Function
def position_type(s):
    """
    This function converts the individual positions (abbreviations) and classifies it as
    either a forward, midfielder, Back, or Goalkeeper
    """
    if (s[-2] == 'T') | (s[-2] == 'W'):
        return 'Forward'
    elif s[-2] == 'M':
        return 'MidFielder'
    elif s[-2] == 'B':
        return 'Back'
    else:
        return 'GoalKeeper'

In [30]:
# Create position type column
df['Preferred Positions Type'] = df['Preferred Positions'].apply(position_type)

# Look at the first 5 entries
df['Preferred Positions Type'].head()

Name
Cristiano Ronaldo       Forward
L. Messi                Forward
Neymar                  Forward
L. Suárez               Forward
M. Neuer             GoalKeeper
Name: Preferred Positions Type, dtype: object

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17981 entries, Cristiano Ronaldo to L. Sackey
Data columns (total 39 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       17981 non-null  int64
 1   Nationality               17981 non-null  object
 2   Overall                   17981 non-null  int64
 3   Acceleration              17981 non-null  object
 4   Aggression                17981 non-null  object
 5   Agility                   17981 non-null  object
 6   Balance                   17981 non-null  object
 7   Ball control              17981 non-null  object
 8   Composure                 17981 non-null  object
 9   Crossing                  17981 non-null  object
 10  Curve                     17981 non-null  object
 11  Dribbling                 17981 non-null  object
 12  Finishing                 17981 non-null  object
 13  Free kick accuracy        17981 non-null  object
 14  GK diving                 17981 non-null  object
 15  GK handling               17981 non-null  object
 16  GK kicking                17981 non-null  object
 17  GK positioning            17981 non-null  object
 18  GK reflexes               17981 non-null  object
 19  Heading accuracy          17981 non-null  object
 20  Interceptions             17981 non-null  object
 21  Jumping                   17981 non-null  object
 22  Long passing              17981 non-null  object
 23  Long shots                17981 non-null  object
 24  Marking                   17981 non-null  object
 25  Penalties                 17981 non-null  object
 26  Positioning               17981 non-null  object
 27  Reactions                 17981 non-null  object
 28  Short passing             17981 non-null  object
 29  Shot power                17981 non-null  object
 30  Sliding tackle            17981 non-null  object
 31  Sprint speed              17981 non-null  object
 32  Stamina                   17981 non-null  object
 33  Standing tackle           17981 non-null  object
 34  Strength                  17981 non-null  object
 35  Vision                    17981 non-null  object
 36  Volleys                   17981 non-null  object
 37  Preferred Positions       17981 non-null  object
 38  Preferred Positions Type  17981 non-null  object
dtypes: int64(2), object(37)
memory usage: 6.0+ MB

## Transforming column types

In [46]:
# Select all numeric attribute columns, i.e. excluding "word-type" columns such as Nationality
cols = ['Overall', 'Acceleration', 'Aggression', 'Agility', 'Balance',
        'Ball control', 'Composure', 'Crossing', 'Curve', 'Dribbling',
        'Finishing', 'Free kick accuracy', 'GK diving', 'GK handling',
        'GK kicking', 'GK positioning', 'GK reflexes', 'Heading accuracy',
        'Interceptions', 'Jumping', 'Long passing', 'Long shots', 'Marking',
        'Penalties', 'Positioning', 'Reactions', 'Short passing', 'Shot power',
        'Sliding tackle', 'Sprint speed', 'Stamina', 'Standing tackle', 'Strength',
        'Vision', 'Volleys']

In [47]:
# Create function
def to_float(x):
    """Transforms numeric attribute columns to type float"""
    if type(x) is int:
        return float(x)
    else:
        return float(x[0:2])

In [48]:
# use the map() function to transform all selected columns
df[cols] = df[cols].map(to_float)

TypeError: 'float' object is not subscriptable

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17981 entries, Cristiano Ronaldo to L. Sackey
Data columns (total 39 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       17981 non-null  int64
 1   Nationality               17981 non-null  object
 2   Overall                   17981 non-null  float64
 3   Acceleration              17981 non-null  float64
 4   Aggression                17981 non-null  float64
 5   Agility                   17981 non-null  float64
 6   Balance                   17981 non-null  float64
 7   Ball control              17981 non-null  float64
 8   Composure                 17981 non-null  float64
 9   Crossing                  17981 non-null  float64
 10  Curve                     17981 non-null  float64
 11  Dribbling                 17981 non-null  float64
 12  Finishing                 17981 non-null  float64
 13  Free kick accuracy        17981 non-null  float64
 14  GK diving                 17981 non-null  float64
 15  GK handling               17981 non-null  float64
 16  GK kicking                17981 non-null  float64
 17  GK positioning            17981 non-null  float64
 18  GK reflexes               17981 non-null  float64
 19  Heading accuracy          17981 non-null  float64
 20  Interceptions             17981 non-null  float64
 21  Jumping                   17981 non-null  float64
 22  Long passing              17981 non-null  float64
 23  Long shots                17981 non-null  float64
 24  Marking                   17981 non-null  float64
 25  Penalties                 17981 non-null  float64
 26  Positioning               17981 non-null  float64
 27  Reactions                 17981 non-null  float64
 28  Short passing             17981 non-null  float64
 29  Shot power                17981 non-null  float64
 30  Sliding tackle            17981 non-null  float64
 31  Sprint speed              17981 non-null  float64
 32  Stamina                   17981 non-null  float64
 33  Standing tackle           17981 non-null  float64
 34  Strength                  17981 non-null  float64
 35  Vision                    17981 non-null  float64
 36  Volleys                   17981 non-null  float64
 37  Preferred Positions       17981 non-null  object
 38  Preferred Positions Type  17981 non-null  object
dtypes: float64(35), int64(1), object(3)
memory usage: 6.0+ MB