### This notebook contains the code exercises meant to help the learner understand and learn how to work with DataFrames

In [2]:
import pandas as pd
import numpy as np

In [4]:
animal_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/Python/Animals.csv')

#### Exercise 1: Filter the dataset to show only species that have an average lifespan (Years) greater than 20 and are classified as vulnerable in conservation status

In [6]:
animal_df.head()

,Species,Average Lifespan (Years),Habitat,Conservation Status
0,African Elephant,60,Grasslands,Vulnerable
1,Bengal Tiger,15,Forests,Endangered
2,Blue Whale,80,Ocean,Endangered
3,Giant Panda,20,Temperate Forest,Vulnerable
4,Komodo Dragon,30,Islands,Vulnerable

In [9]:
avg_lf_animals_df = animal_df[(animal_df["Average Lifespan (Years)"] > 20) & (animal_df["Conservation Status"] == "Vulnerable")]

print(avg_lf_animals_df)

            Species  Average Lifespan (Years)     Habitat Conservation Status
0  African Elephant                        60  Grasslands          Vulnerable
4     Komodo Dragon                        30     Islands          Vulnerable
5        Polar Bear                        25      Arctic          Vulnerable

#### Exercise 2: Creating a new column and deleting it from a DataFrame

In [22]:
# Creating the Column
animal_df['Lifespan in Months'] = animal_df['Average Lifespan (Years)'] * 12

animal_df.head()

,Species,Average Lifespan (Years),Habitat,Conservation Status,Lifespan in Months
0,African Elephant,60,Grasslands,Vulnerable,720
1,Bengal Tiger,15,Forests,Endangered,180
2,Blue Whale,80,Ocean,Endangered,960
3,Giant Panda,20,Temperate Forest,Vulnerable,240
4,Komodo Dragon,30,Islands,Vulnerable,360

In [24]:
# Dropping the column
animal_df.drop('Lifespan in Months', axis=1).head()

,Species,Average Lifespan (Years),Habitat,Conservation Status
0,African Elephant,60,Grasslands,Vulnerable
1,Bengal Tiger,15,Forests,Endangered
2,Blue Whale,80,Ocean,Endangered
3,Giant Panda,20,Temperate Forest,Vulnerable
4,Komodo Dragon,30,Islands,Vulnerable

#### Exercise 3: Filtering Dataframes and suing apply and lambda on Dataframes

In [27]:
# Filter the data
long_lived_species = animal_df[animal_df['Average Lifespan (Years)'] > 50]

long_lived_species

,Species,Average Lifespan (Years),Habitat,Conservation Status,Lifespan in Months
0,African Elephant,60,Grasslands,Vulnerable,720
2,Blue Whale,80,Ocean,Endangered,960
13,Green Sea Turtle,80,"Oceans, Beaches",Endangered,960

In [29]:
# Convert Average Lifespan (Years) of all species into the float data type in long_lived_species

long_lived_species.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 13
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Species                   3 non-null      object
 1   Average Lifespan (Years)  3 non-null      int64
 2   Habitat                   3 non-null      object
 3   Conservation Status       3 non-null      object
 4   Lifespan in Months        3 non-null      int64
dtypes: int64(2), object(3)
memory usage: 144.0+ bytes

In [32]:
long_lived_species['Average Lifespan (Years)'] = long_lived_species['Average Lifespan (Years)'].apply(lambda x: float(x))

long_lived_species.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 13
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Species                   3 non-null      object
 1   Average Lifespan (Years)  3 non-null      float64
 2   Habitat                   3 non-null      object
 3   Conservation Status       3 non-null      object
 4   Lifespan in Months        3 non-null      int64
dtypes: float64(1), int64(1), object(3)
memory usage: 144.0+ bytes

C:\Users\steph\AppData\Local\Temp\ipykernel_36232\1529736562.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  long_lived_species['Average Lifespan (Years)'] = long_lived_species['Average Lifespan (Years)'].apply(lambda x: float(x))

#### Exercise 4: Listing all columns for species that have the string "endangered" as part of their conservation status

In [39]:
animal_df.head()

,Species,Average Lifespan (Years),Habitat,Conservation Status,Lifespan in Months
0,African Elephant,60,Grasslands,Vulnerable,720
1,Bengal Tiger,15,Forests,Endangered,180
2,Blue Whale,80,Ocean,Endangered,960
3,Giant Panda,20,Temperate Forest,Vulnerable,240
4,Komodo Dragon,30,Islands,Vulnerable,360

In [56]:
# animal_df[animal_df['Conservation Status'] == 'Endangered']

# Filtering to find species with 'Endangered' in their conservation status
Endangered_species = animal_df[animal_df['Conservation Status'].str.contains('Endangered')]

# Display the filtered DataFrame
Endangered_species

,Species,Average Lifespan (Years),Habitat,Conservation Status,Lifespan in Months,Threat Level
1,Bengal Tiger,15,Forests,Endangered,180,High
2,Blue Whale,80,Ocean,Endangered,960,High
9,Orangutan,35,Rainforests,Critically Endangered,420,High
13,Green Sea Turtle,80,"Oceans, Beaches",Endangered,960,High

#### Exercise 5: Listing the average lifespan of species for each habitat in descending order

In [57]:
animal_df.groupby('Habitat')['Average Lifespan (Years)'].mean().sort_values(ascending=False)

Habitat
Ocean                 80.0
Oceans, Beaches       80.0
Grasslands            60.0
Rainforests           35.0
Islands               30.0
Arctic                25.0
Antarctic             20.0
Forests, Seacoasts    20.0
Temperate Forest      20.0
Forests               15.0
Mountain Ranges       15.0
Savanna               14.0
Eucalyptus Forests    13.0
Forests, Tundra        8.0
Various                5.0
Name: Average Lifespan (Years), dtype: float64

In [45]:
animal_df.head()

,Species,Average Lifespan (Years),Habitat,Conservation Status,Lifespan in Months
0,African Elephant,60,Grasslands,Vulnerable,720
1,Bengal Tiger,15,Forests,Endangered,180
2,Blue Whale,80,Ocean,Endangered,960
3,Giant Panda,20,Temperate Forest,Vulnerable,240
4,Komodo Dragon,30,Islands,Vulnerable,360

#### Exercise 6: Creating a column that categorizes species into different classes based on their conservation status

In [51]:
animal_df['Threat Level'] = animal_df['Conservation Status'].apply(
    lambda status:
        'High' if status in ['Critically Endangered', 'Endangered'] else
        'Medium' if status in ['Vulnerable', 'Near Threatened'] else
        'Low'
)

animal_df.head()

,Species,Average Lifespan (Years),Habitat,Conservation Status,Lifespan in Months,Threat Level
0,African Elephant,60,Grasslands,Vulnerable,720,Medium
1,Bengal Tiger,15,Forests,Endangered,180,High
2,Blue Whale,80,Ocean,Endangered,960,High
3,Giant Panda,20,Temperate Forest,Vulnerable,240,Medium
4,Komodo Dragon,30,Islands,Vulnerable,360,Medium