## **Exercise: Binary Classification metrics**

#### In this exercise, we train a logistic regression model and evaluate its performance by calculating overall accuracy from its confusion matrix.

### **Learning Objectives**
#### By the end of this notebook, you should be able to:
#### - Train a logistic regression model
#### - Calculate the model's overall accuracy

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [2]:
# load dataset
habitat_df = pd.read_csv("https://raw.githubusercontent.com/Explore-AI/Public-Data/master/habitat_suitability.csv")
habitat_df.head(5)

,Average Temperature (°C),Annual Rainfall (mm),Vegetation Density (% coverage),Predator Presence (0 or 1),Human Disturbance Index,Altitude (meters),Water Source Availability (0 or 1),Habitat Suitability
0,20.009527,1270.407873,90.142754,1,0.392750,355.433041,1,1
1,16.228576,1419.881504,58.246594,0,0.356556,64.890245,1,1
2,25.472638,991.750374,57.898060,1,0.832856,301.426259,1,0
3,34.030446,1431.824231,41.892067,1,0.044347,390.152269,1,0
4,38.334526,1018.262946,56.814597,1,0.308421,450.584113,1,0

### Exercises

#### Using the dataset, we want to build a classification model that will be able to classify habitats as suitable (1) or unsuitable (0).

#### In the code below, we prepare the dataset and train a logistic regression model following these preliminary steps

In [3]:
# prepare the data
X = habitat_df.drop('Habitat Suitability', axis=1) # Features
y = habitat_df['Habitat Suitability'] # Target variable

# split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

# Train a logistic regression model
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

LogisticRegression()

### Exercise 1

#### a) Now that we have trained a logisitic regression model on the `habitat_suitability` dataset, let's try and get information on how our model performs on new unseen data.

#### Hence:
#### 1. Use the trained logisitc regression model to make predictions on the test set.
#### 2. Import and use `confusion_matrix` from `sklearn.metrics` to generate the confusion matrix for your predictions.
#### 3. Display the confusion matrix.

#### **Note:** Remember to scale the test set features to ensure consistency

In [7]:
X_test_scaled = scaler.transform(X_test)

y_pred = model.predict(X_test_scaled)

In [8]:
from sklearn.metrics import confusion_matrix

In [9]:
cm = confusion_matrix(y_test, y_pred)

In [10]:
print(cm)

[[143   9]
 [ 16  32]]

#### b) The confusion matrix is not easy to read. Let's improve on this by converting it into a DataFrame with the following row and column labels `0: Unsuitable` and `1: Suitable`

In [11]:
labels = ['0: Unsuitable', '1: Suitable']

In [12]:
cm_df = pd.DataFrame(data=cm, index=labels, columns=labels)

In [13]:
cm_df

               0: Unsuitable  1: Suitable
0: Unsuitable            143            9
1: Suitable               16           32

### Exercise 2

#### Now that we can easily interpret our confusion matrix, we want to compare the distribution of the ground truth classifications and the classifications made by the model.

#### That is, we want to find out how many observations were classified as suitable (1) and unsuitable (0) habitats by the model and compare this to the counts originally in the test set.

In [16]:
actual_counts = y_test.value_counts().sort_index()

predicted_counts = pd.Series(y_pred).value_counts().sort_index()

In [17]:
comparison = pd.DataFrame({
    'Ground Truth': actual_counts,
    'Model Prediction': predicted_counts
})

In [19]:
comparison.index = ['0: Unsuitable', '1: Suitable']

In [20]:
comparison

               Ground Truth  Model Prediction
0: Unsuitable           152               159
1: Suitable              48                41

### Exercise 3

#### From the multidimensional array `conf_matrix`, access the true positive, true negative, false positive, and false negative values and store them in the following variables `TP`, `TN`, `FP`, and `FN`, respectively.

#### Print each value together with its label.

#### **Hint:** Apply your knowledge of where each of these values is located in the confusion matrix

In [21]:
cm

array([[143,   9],
       [ 16,  32]], dtype=int64)

In [26]:
TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]

print(f'True Positive: {TP}')
print(f'True Negative: {TN}')
print(f'False Positive: {FP}')
print(f'False Negative: {FN}')

True Positive: 32
True Negative: 143
False Positive: 9
False Negative: 16

### **Exercise 4**

#### Let's now find out the overall accuracy of our model

#### a) Using the values from **Exercise 3**, calculate the overall accuracy using the formula: Accuracy=Correct predictions / Total predictions

In [27]:
from sklearn.metrics import accuracy_score

In [29]:
accuracy = accuracy_score(y_test, y_pred)

print(accuracy)

0.875